# Generated by Django 4.1 on 2022-08-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
