# Generated by Django 4.1 on 2022-08-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0005_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
