# Generated by Django 4.1 on 2022-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0006_alter_comment_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(db_column='rating_post', default=0),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='_rating_post',
        ),
    ]
