# Generated by Django 4.1 on 2022-08-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0007_alter_post_rating_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_rating_post',
            new_name='rating_post',
        ),
    ]
