# Generated by Django 4.1 on 2022-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0008_rename__rating_post_post_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0),
        ),
    ]
